name: Donation Reminder

on:
  schedule:
    - cron: "0 12 * * 1" # every monday
    - cron: "0 10 * * 4" # every thursday
  workflow_dispatch:

jobs:
  server-boost-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read message content
        id: message
        run: echo "content=$(cat messages/donation.md)" >> $GITHUB_OUTPUT

      - name: Send Message to Discord
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          avatar-url: https://raw.githubusercontent.com/${{ github.repository }}/master/images/Profile%20Logo%20Kofi.png
          username: Seelen
          embed-color: 0xf76206
          embed-title: Support Seelen's Development ðŸ’–
          embed-description: ${{ steps.message.outputs.content }}
          embed-footer-text: '#SupportOpenSource'
