name: Server Boost Reminder

on:
  schedule:
    - cron: "0 12 * * 1" # every monday
    - cron: "0 10 * * 4" # every thursday
  workflow_dispatch:

jobs:
  server-boost-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Send Message to Discord
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          avatar-url: https://raw.githubusercontent.com/eythaann/Seelen-UI/refs/heads/master/static/icons/profile_ko-fi.png
          username: Seelen
          embed-color: 0xa94609
          embed-title: Support Seelen's Development ğŸ’–
          embed-description: |-
            Enjoying Seelen UI? Consider supporting the project through donations!

            **Your support helps:**
            â†’ ğŸ› ï¸ Fund ongoing development and maintenance
            â†’ ğŸš€ Accelerate new features and improvements
            â†’ ğŸ’» Cover server and infrastructure costs

            **Ways to support:**
            <:kofi:1353984463855550505> [Ko-fi](https://ko-fi.com/eythaann)
            <:patreon:1354044241898115082> [Patreon](https://patreon.com/eythaann)
            <:github:1354043810568470578> [GitHub Sponsors](https://github.com/sponsors/eythaann)

            Every contribution, big or small, is appreciated! âœ¨

            *#SupportOpenSource*
          embed-footer-text: Thank you for being part of our community!
